package autogen

// AutoGenerated is an autogenerated type from JSON.
type AutoGenerated struct {
	ClosedBucket string  `json:"closed_bucket,omitempty"`
	DateClosed   string  `json:"date_closed,omitempty"`
	Description  string  `json:"description,omitempty"`
	Distance     float64 `json:"distance,omitempty"`
	Email        string  `json:"email,omitempty"`
	Fax          string  `json:"fax,omitempty"`
	Features     struct {
		Amenities struct {
			Atm            any `json:"atm,omitempty"`
			CoatCheck      any `json:"coat_check,omitempty"`
			Jukebox        any `json:"jukebox,omitempty"`
			LiveMusic      any `json:"live_music,omitempty"`
			Music          any `json:"music,omitempty"`
			OutdoorSeating any `json:"outdoor_seating,omitempty"`
			Parking        struct {
				Parking       any `json:"parking,omitempty"`
				PrivateLot    any `json:"private_lot,omitempty"`
				PublicLot     any `json:"public_lot,omitempty"`
				StreetParking any `json:"street_parking,omitempty"`
				ValetParking  any `json:"valet_parking,omitempty"`
			} `json:"parking,omitempty"`
			PrivateRoom          any    `json:"private_room,omitempty"`
			Restroom             any    `json:"restroom,omitempty"`
			SitDownDining        any    `json:"sit_down_dining,omitempty"`
			Smoking              any    `json:"smoking,omitempty"`
			Tvs                  any    `json:"tvs,omitempty"`
			WheelchairAccessible any    `json:"wheelchair_accessible,omitempty"`
			Wifi                 string `json:"wifi,omitempty"`
		} `json:"amenities,omitempty"`
		Attributes struct {
			BusinessMeeting string `json:"business_meeting,omitempty"`
			Clean           string `json:"clean,omitempty"`
			Crowded         string `json:"crowded,omitempty"`
			DatesPopular    string `json:"dates_popular,omitempty"`
			Dressy          string `json:"dressy,omitempty"`
			FamiliesPopular string `json:"families_popular,omitempty"`
			GlutenFreeDiet  string `json:"gluten_free_diet,omitempty"`
			GoodForDogs     string `json:"good_for_dogs,omitempty"`
			GroupsPopular   string `json:"groups_popular,omitempty"`
			HealthyDiet     string `json:"healthy_diet,omitempty"`
			LateNight       string `json:"late_night,omitempty"`
			Noisy           string `json:"noisy,omitempty"`
			QuickBite       string `json:"quick_bite,omitempty"`
			Romantic        string `json:"romantic,omitempty"`
			ServiceQuality  string `json:"service_quality,omitempty"`
			SinglesPopular  string `json:"singles_popular,omitempty"`
			SpecialOccasion string `json:"special_occasion,omitempty"`
			Trendy          string `json:"trendy,omitempty"`
			ValueForMoney   string `json:"value_for_money,omitempty"`
			VeganDiet       string `json:"vegan_diet,omitempty"`
			VegetarianDiet  string `json:"vegetarian_diet,omitempty"`
		} `json:"attributes,omitempty"`
		FoodAndDrink struct {
			Alcohol struct {
				BarService any `json:"bar_service,omitempty"`
				Beer       any `json:"beer,omitempty"`
				Byo        any `json:"byo,omitempty"`
				Cocktails  any `json:"cocktails,omitempty"`
				FullBar    any `json:"full_bar,omitempty"`
				Wine       any `json:"wine,omitempty"`
			} `json:"alcohol,omitempty"`
			Meals struct {
				BarSnacks   any `json:"bar_snacks,omitempty"`
				Breakfast   any `json:"breakfast,omitempty"`
				Brunch      any `json:"brunch,omitempty"`
				Dessert     any `json:"dessert,omitempty"`
				Dinner      any `json:"dinner,omitempty"`
				HappyHour   any `json:"happy_hour,omitempty"`
				Lunch       any `json:"lunch,omitempty"`
				TastingMenu any `json:"tasting_menu,omitempty"`
			} `json:"meals,omitempty"`
		} `json:"food_and_drink,omitempty"`
		Payment struct {
			CreditCards struct {
				AcceptsCreditCards any `json:"accepts_credit_cards,omitempty"`
				Amex               any `json:"amex,omitempty"`
				DinersClub         any `json:"diners_club,omitempty"`
				Discover           any `json:"discover,omitempty"`
				MasterCard         any `json:"master_card,omitempty"`
				UnionPay           any `json:"union_pay,omitempty"`
				Visa               any `json:"visa,omitempty"`
			} `json:"credit_cards,omitempty"`
			DigitalWallet struct {
				AcceptsNfc any `json:"accepts_nfc,omitempty"`
			} `json:"digital_wallet,omitempty"`
		} `json:"payment,omitempty"`
		Services struct {
			Delivery any `json:"delivery,omitempty"`
			DineIn   struct {
				EssentialReservations  any `json:"essential_reservations,omitempty"`
				GroupsOnlyReservations any `json:"groups_only_reservations,omitempty"`
				OnlineReservations     any `json:"online_reservations,omitempty"`
				Reservations           any `json:"reservations,omitempty"`
			} `json:"dine_in,omitempty"`
			DriveThrough any `json:"drive_through,omitempty"`
			Takeout      any `json:"takeout,omitempty"`
		} `json:"services,omitempty"`
	} `json:"features,omitempty"`
	FsqID    string `json:"fsq_id,omitempty"`
	Geocodes struct {
		DropOff struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"drop_off,omitempty"`
		FrontDoor struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"front_door,omitempty"`
		Main struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"main,omitempty"`
		Road struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"road,omitempty"`
		Roof struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"roof,omitempty"`
	} `json:"geocodes,omitempty"`
	Hours struct {
		Display        string `json:"display,omitempty"`
		IsLocalHoliday bool   `json:"is_local_holiday,omitempty"`
		OpenNow        bool   `json:"open_now,omitempty"`
	} `json:"hours,omitempty"`
	Link     string `json:"link,omitempty"`
	Location struct {
		Address          string `json:"address,omitempty"`
		AddressExtended  string `json:"address_extended,omitempty"`
		AdminRegion      string `json:"admin_region,omitempty"`
		CensusBlock      string `json:"census_block,omitempty"`
		Country          string `json:"country,omitempty"`
		CrossStreet      string `json:"cross_street,omitempty"`
		Dma              string `json:"dma,omitempty"`
		FormattedAddress string `json:"formatted_address,omitempty"`
		Locality         string `json:"locality,omitempty"`
		PoBox            string `json:"po_box,omitempty"`
		PostTown         string `json:"post_town,omitempty"`
		Postcode         string `json:"postcode,omitempty"`
		Region           string `json:"region,omitempty"`
	} `json:"location,omitempty"`
	Menu          string  `json:"menu,omitempty"`
	Name          string  `json:"name,omitempty"`
	Popularity    float64 `json:"popularity,omitempty"`
	Price         float64 `json:"price,omitempty"`
	Rating        float64 `json:"rating,omitempty"`
	RelatedPlaces any     `json:"related_places,omitempty"`
	SocialMedia   struct {
		FacebookID string `json:"facebook_id,omitempty"`
		Instagram  string `json:"instagram,omitempty"`
		Twitter    string `json:"twitter,omitempty"`
	} `json:"social_media,omitempty"`
	Stats struct {
		TotalPhotos  float64 `json:"total_photos,omitempty"`
		TotalRatings float64 `json:"total_ratings,omitempty"`
		TotalTips    float64 `json:"total_tips,omitempty"`
	} `json:"stats,omitempty"`
	StoreID            string `json:"store_id,omitempty"`
	Tel                string `json:"tel,omitempty"`
	Timezone           string `json:"timezone,omitempty"`
	VenueRealityBucket string `json:"venue_reality_bucket,omitempty"`
	Verified           bool   `json:"verified,omitempty"`
	Website            string `json:"website,omitempty"`
}
