package autogen

type AutoGenerated struct {
	Hours struct {
		Display          string `json:"display,omitempty"`
		Is_local_holiday bool   `json:"is_local_holiday,omitempty"`
		Open_now         bool   `json:"open_now,omitempty"`
	} `json:"hours,omitempty"`
	Social_media struct {
		Facebook_id string `json:"facebook_id,omitempty"`
		Instagram   string `json:"instagram,omitempty"`
		Twitter     string `json:"twitter,omitempty"`
	} `json:"social_media,omitempty"`
	Link        string `json:"link,omitempty"`
	Fsq_id      string `json:"fsq_id,omitempty"`
	Date_closed string `json:"date_closed,omitempty"`
	Geocodes    struct {
		Drop_off struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"drop_off,omitempty"`
		Front_door struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"front_door,omitempty"`
		Main struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"main,omitempty"`
		Road struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"road,omitempty"`
		Roof struct {
			Latitude  float64 `json:"latitude,omitempty"`
			Longitude float64 `json:"longitude,omitempty"`
		} `json:"roof,omitempty"`
	} `json:"geocodes,omitempty"`
	Store_id       string  `json:"store_id,omitempty"`
	Name           string  `json:"name,omitempty"`
	Price          float64 `json:"price,omitempty"`
	Description    string  `json:"description,omitempty"`
	Timezone       string  `json:"timezone,omitempty"`
	Fax            string  `json:"fax,omitempty"`
	Popularity     float64 `json:"popularity,omitempty"`
	Tel            string  `json:"tel,omitempty"`
	Menu           string  `json:"menu,omitempty"`
	Related_places any     `json:"related_places,omitempty"`
	Website        string  `json:"website,omitempty"`
	Stats          struct {
		Total_tips    float64 `json:"total_tips,omitempty"`
		Total_photos  float64 `json:"total_photos,omitempty"`
		Total_ratings float64 `json:"total_ratings,omitempty"`
	} `json:"stats,omitempty"`
	Venue_reality_bucket string `json:"venue_reality_bucket,omitempty"`
	Email                string `json:"email,omitempty"`
	Verified             bool   `json:"verified,omitempty"`
	Location             struct {
		Address_extended  string `json:"address_extended,omitempty"`
		Postcode          string `json:"postcode,omitempty"`
		Locality          string `json:"locality,omitempty"`
		Address           string `json:"address,omitempty"`
		Dma               string `json:"dma,omitempty"`
		Po_box            string `json:"po_box,omitempty"`
		Region            string `json:"region,omitempty"`
		Admin_region      string `json:"admin_region,omitempty"`
		Country           string `json:"country,omitempty"`
		Census_block      string `json:"census_block,omitempty"`
		Post_town         string `json:"post_town,omitempty"`
		Formatted_address string `json:"formatted_address,omitempty"`
		Cross_street      string `json:"cross_street,omitempty"`
	} `json:"location,omitempty"`
	Closed_bucket string  `json:"closed_bucket,omitempty"`
	Distance      float64 `json:"distance,omitempty"`
	Rating        float64 `json:"rating,omitempty"`
	Features      struct {
		Services struct {
			Delivery      any `json:"delivery,omitempty"`
			Takeout       any `json:"takeout,omitempty"`
			Drive_through any `json:"drive_through,omitempty"`
			Dine_in       struct {
				Reservations             any `json:"reservations,omitempty"`
				Online_reservations      any `json:"online_reservations,omitempty"`
				Groups_only_reservations any `json:"groups_only_reservations,omitempty"`
				Essential_reservations   any `json:"essential_reservations,omitempty"`
			} `json:"dine_in,omitempty"`
		} `json:"services,omitempty"`
		Amenities struct {
			Jukebox               any `json:"jukebox,omitempty"`
			Atm                   any `json:"atm,omitempty"`
			Restroom              any `json:"restroom,omitempty"`
			Tvs                   any `json:"tvs,omitempty"`
			Live_music            any `json:"live_music,omitempty"`
			Wheelchair_accessible any `json:"wheelchair_accessible,omitempty"`
			Parking               struct {
				Public_lot     any `json:"public_lot,omitempty"`
				Private_lot    any `json:"private_lot,omitempty"`
				Parking        any `json:"parking,omitempty"`
				Street_parking any `json:"street_parking,omitempty"`
				Valet_parking  any `json:"valet_parking,omitempty"`
			} `json:"parking,omitempty"`
			Coat_check      any    `json:"coat_check,omitempty"`
			Wifi            string `json:"wifi,omitempty"`
			Outdoor_seating any    `json:"outdoor_seating,omitempty"`
			Smoking         any    `json:"smoking,omitempty"`
			Sit_down_dining any    `json:"sit_down_dining,omitempty"`
			Private_room    any    `json:"private_room,omitempty"`
			Music           any    `json:"music,omitempty"`
		} `json:"amenities,omitempty"`
		Attributes struct {
			Trendy           string `json:"trendy,omitempty"`
			Vegetarian_diet  string `json:"vegetarian_diet,omitempty"`
			Good_for_dogs    string `json:"good_for_dogs,omitempty"`
			Crowded          string `json:"crowded,omitempty"`
			Gluten_free_diet string `json:"gluten_free_diet,omitempty"`
			Healthy_diet     string `json:"healthy_diet,omitempty"`
			Families_popular string `json:"families_popular,omitempty"`
			Dates_popular    string `json:"dates_popular,omitempty"`
			Business_meeting string `json:"business_meeting,omitempty"`
			Late_night       string `json:"late_night,omitempty"`
			Service_quality  string `json:"service_quality,omitempty"`
			Quick_bite       string `json:"quick_bite,omitempty"`
			Singles_popular  string `json:"singles_popular,omitempty"`
			Vegan_diet       string `json:"vegan_diet,omitempty"`
			Noisy            string `json:"noisy,omitempty"`
			Special_occasion string `json:"special_occasion,omitempty"`
			Groups_popular   string `json:"groups_popular,omitempty"`
			Clean            string `json:"clean,omitempty"`
			Romantic         string `json:"romantic,omitempty"`
			Value_for_money  string `json:"value_for_money,omitempty"`
			Dressy           string `json:"dressy,omitempty"`
		} `json:"attributes,omitempty"`
		Payment struct {
			Credit_cards struct {
				Accepts_credit_cards any `json:"accepts_credit_cards,omitempty"`
				Amex                 any `json:"amex,omitempty"`
				Discover             any `json:"discover,omitempty"`
				Visa                 any `json:"visa,omitempty"`
				Diners_club          any `json:"diners_club,omitempty"`
				Master_card          any `json:"master_card,omitempty"`
				Union_pay            any `json:"union_pay,omitempty"`
			} `json:"credit_cards,omitempty"`
			Digital_wallet struct {
				Accepts_nfc any `json:"accepts_nfc,omitempty"`
			} `json:"digital_wallet,omitempty"`
		} `json:"payment,omitempty"`
		Food_and_drink struct {
			Alcohol struct {
				Wine        any `json:"wine,omitempty"`
				Bar_service any `json:"bar_service,omitempty"`
				Beer        any `json:"beer,omitempty"`
				Byo         any `json:"byo,omitempty"`
				Cocktails   any `json:"cocktails,omitempty"`
				Full_bar    any `json:"full_bar,omitempty"`
			} `json:"alcohol,omitempty"`
			Meals struct {
				Happy_hour   any `json:"happy_hour,omitempty"`
				Dessert      any `json:"dessert,omitempty"`
				Dinner       any `json:"dinner,omitempty"`
				Tasting_menu any `json:"tasting_menu,omitempty"`
				Bar_snacks   any `json:"bar_snacks,omitempty"`
				Breakfast    any `json:"breakfast,omitempty"`
				Brunch       any `json:"brunch,omitempty"`
				Lunch        any `json:"lunch,omitempty"`
			} `json:"meals,omitempty"`
		} `json:"food_and_drink,omitempty"`
	} `json:"features,omitempty"`
}
