package main

import (
	"encoding/json"
	"os"
	"testing"

	sample00gen "github.com/wcharczuk/json2go/testdata/sample_00_gen"
	samplegen "github.com/wcharczuk/json2go/testdata/sample_gen"
)

func Test_sample(t *testing.T) {
	testData, err := os.ReadFile("testdata/sample.json")
	if err != nil {
		t.Fail()
	}

	var output samplegen.AutoGenerated
	err = json.Unmarshal(testData, &output)
	if err != nil {
		t.Errorf("%+v\n", err)
		t.Fail()
	}
}
func Test_sample_00(t *testing.T) {
	testData, err := os.ReadFile("testdata/sample_00.json")
	if err != nil {
		t.Fail()
	}

	var output sample00gen.AutoGenerated
	err = json.Unmarshal(testData, &output)
	if err != nil {
		t.Errorf("%+v\n", err)
		t.Fail()
	}
}
