package main

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/wcharczuk/json2go/testdata/autogen"
)

func Test_formatWithName(t *testing.T) {
	testData, err := os.ReadFile("testdata/sample.json")
	if err != nil {
		t.Fail()
	}

	var output autogen.AutoGenerated
	err = json.Unmarshal(testData, &output)
	if err != nil {
		t.Errorf("%+v\n", err)
		t.Fail()
	}
}
