package autogen

// AutoGenerated is an autogenerated type from JSON.
type AutoGenerated struct {
	Categories []struct {
		Icon       AutoGenerated_Categories_Icon `json:"icon,omitempty"`
		ID         float64                       `json:"id,omitempty"`
		Name       string                        `json:"name,omitempty"`
		PluralName string                        `json:"plural_name,omitempty"`
		ShortName  string                        `json:"short_name,omitempty"`
	} `json:"categories,omitempty"`
	Chains []struct {
		ID   string `json:"id,omitempty"`
		Name string `json:"name,omitempty"`
	} `json:"chains,omitempty"`
	ClosedBucket string  `json:"closed_bucket,omitempty"`
	DateClosed   string  `json:"date_closed,omitempty"`
	Description  string  `json:"description,omitempty"`
	Distance     float64 `json:"distance,omitempty"`
	Email        string  `json:"email,omitempty"`
	Fax          string  `json:"fax,omitempty"`
	Features     struct {
		Amenities struct {
			Atm            AutoGenerated_Features_Amenities_Atm `json:"atm,omitempty"`
			CoatCheck      AutoGenerated_Features_Amenities_Atm `json:"coat_check,omitempty"`
			Jukebox        AutoGenerated_Features_Amenities_Atm `json:"jukebox,omitempty"`
			LiveMusic      AutoGenerated_Features_Amenities_Atm `json:"live_music,omitempty"`
			Music          AutoGenerated_Features_Amenities_Atm `json:"music,omitempty"`
			OutdoorSeating AutoGenerated_Features_Amenities_Atm `json:"outdoor_seating,omitempty"`
			Parking        struct {
				Parking       AutoGenerated_Features_Amenities_Atm `json:"parking,omitempty"`
				PrivateLot    AutoGenerated_Features_Amenities_Atm `json:"private_lot,omitempty"`
				PublicLot     AutoGenerated_Features_Amenities_Atm `json:"public_lot,omitempty"`
				StreetParking AutoGenerated_Features_Amenities_Atm `json:"street_parking,omitempty"`
				ValetParking  AutoGenerated_Features_Amenities_Atm `json:"valet_parking,omitempty"`
			} `json:"parking,omitempty"`
			PrivateRoom          AutoGenerated_Features_Amenities_Atm `json:"private_room,omitempty"`
			Restroom             AutoGenerated_Features_Amenities_Atm `json:"restroom,omitempty"`
			SitDownDining        AutoGenerated_Features_Amenities_Atm `json:"sit_down_dining,omitempty"`
			Smoking              AutoGenerated_Features_Amenities_Atm `json:"smoking,omitempty"`
			Tvs                  AutoGenerated_Features_Amenities_Atm `json:"tvs,omitempty"`
			WheelchairAccessible AutoGenerated_Features_Amenities_Atm `json:"wheelchair_accessible,omitempty"`
			Wifi                 string                               `json:"wifi,omitempty"`
		} `json:"amenities,omitempty"`
		Attributes struct {
			BusinessMeeting string `json:"business_meeting,omitempty"`
			Clean           string `json:"clean,omitempty"`
			Crowded         string `json:"crowded,omitempty"`
			DatesPopular    string `json:"dates_popular,omitempty"`
			Dressy          string `json:"dressy,omitempty"`
			FamiliesPopular string `json:"families_popular,omitempty"`
			GlutenFreeDiet  string `json:"gluten_free_diet,omitempty"`
			GoodForDogs     string `json:"good_for_dogs,omitempty"`
			GroupsPopular   string `json:"groups_popular,omitempty"`
			HealthyDiet     string `json:"healthy_diet,omitempty"`
			LateNight       string `json:"late_night,omitempty"`
			Noisy           string `json:"noisy,omitempty"`
			QuickBite       string `json:"quick_bite,omitempty"`
			Romantic        string `json:"romantic,omitempty"`
			ServiceQuality  string `json:"service_quality,omitempty"`
			SinglesPopular  string `json:"singles_popular,omitempty"`
			SpecialOccasion string `json:"special_occasion,omitempty"`
			Trendy          string `json:"trendy,omitempty"`
			ValueForMoney   string `json:"value_for_money,omitempty"`
			VeganDiet       string `json:"vegan_diet,omitempty"`
			VegetarianDiet  string `json:"vegetarian_diet,omitempty"`
		} `json:"attributes,omitempty"`
		FoodAndDrink struct {
			Alcohol struct {
				BarService AutoGenerated_Features_Amenities_Atm `json:"bar_service,omitempty"`
				Beer       AutoGenerated_Features_Amenities_Atm `json:"beer,omitempty"`
				Byo        AutoGenerated_Features_Amenities_Atm `json:"byo,omitempty"`
				Cocktails  AutoGenerated_Features_Amenities_Atm `json:"cocktails,omitempty"`
				FullBar    AutoGenerated_Features_Amenities_Atm `json:"full_bar,omitempty"`
				Wine       AutoGenerated_Features_Amenities_Atm `json:"wine,omitempty"`
			} `json:"alcohol,omitempty"`
			Meals struct {
				BarSnacks   AutoGenerated_Features_Amenities_Atm `json:"bar_snacks,omitempty"`
				Breakfast   AutoGenerated_Features_Amenities_Atm `json:"breakfast,omitempty"`
				Brunch      AutoGenerated_Features_Amenities_Atm `json:"brunch,omitempty"`
				Dessert     AutoGenerated_Features_Amenities_Atm `json:"dessert,omitempty"`
				Dinner      AutoGenerated_Features_Amenities_Atm `json:"dinner,omitempty"`
				HappyHour   AutoGenerated_Features_Amenities_Atm `json:"happy_hour,omitempty"`
				Lunch       AutoGenerated_Features_Amenities_Atm `json:"lunch,omitempty"`
				TastingMenu AutoGenerated_Features_Amenities_Atm `json:"tasting_menu,omitempty"`
			} `json:"meals,omitempty"`
		} `json:"food_and_drink,omitempty"`
		Payment struct {
			CreditCards struct {
				AcceptsCreditCards AutoGenerated_Features_Amenities_Atm `json:"accepts_credit_cards,omitempty"`
				Amex               AutoGenerated_Features_Amenities_Atm `json:"amex,omitempty"`
				DinersClub         AutoGenerated_Features_Amenities_Atm `json:"diners_club,omitempty"`
				Discover           AutoGenerated_Features_Amenities_Atm `json:"discover,omitempty"`
				MasterCard         AutoGenerated_Features_Amenities_Atm `json:"master_card,omitempty"`
				UnionPay           AutoGenerated_Features_Amenities_Atm `json:"union_pay,omitempty"`
				Visa               AutoGenerated_Features_Amenities_Atm `json:"visa,omitempty"`
			} `json:"credit_cards,omitempty"`
			DigitalWallet struct {
				AcceptsNfc AutoGenerated_Features_Amenities_Atm `json:"accepts_nfc,omitempty"`
			} `json:"digital_wallet,omitempty"`
		} `json:"payment,omitempty"`
		Services struct {
			Delivery AutoGenerated_Features_Amenities_Atm `json:"delivery,omitempty"`
			DineIn   struct {
				EssentialReservations  AutoGenerated_Features_Amenities_Atm `json:"essential_reservations,omitempty"`
				GroupsOnlyReservations AutoGenerated_Features_Amenities_Atm `json:"groups_only_reservations,omitempty"`
				OnlineReservations     AutoGenerated_Features_Amenities_Atm `json:"online_reservations,omitempty"`
				Reservations           AutoGenerated_Features_Amenities_Atm `json:"reservations,omitempty"`
			} `json:"dine_in,omitempty"`
			DriveThrough AutoGenerated_Features_Amenities_Atm `json:"drive_through,omitempty"`
			Takeout      AutoGenerated_Features_Amenities_Atm `json:"takeout,omitempty"`
		} `json:"services,omitempty"`
	} `json:"features,omitempty"`
	FsqID    string `json:"fsq_id,omitempty"`
	Geocodes struct {
		DropOff   AutoGenerated_Geocodes_DropOff `json:"drop_off,omitempty"`
		FrontDoor AutoGenerated_Geocodes_DropOff `json:"front_door,omitempty"`
		Main      AutoGenerated_Geocodes_DropOff `json:"main,omitempty"`
		Road      AutoGenerated_Geocodes_DropOff `json:"road,omitempty"`
		Roof      AutoGenerated_Geocodes_DropOff `json:"roof,omitempty"`
	} `json:"geocodes,omitempty"`
	Hours struct {
		Display        string                        `json:"display,omitempty"`
		IsLocalHoliday bool                          `json:"is_local_holiday,omitempty"`
		OpenNow        bool                          `json:"open_now,omitempty"`
		Regular        []AutoGenerated_Hours_Regular `json:"regular,omitempty"`
	} `json:"hours,omitempty"`
	HoursPopular []AutoGenerated_Hours_Regular `json:"hours_popular,omitempty"`
	Link         string                        `json:"link,omitempty"`
	Location     struct {
		Address          string   `json:"address,omitempty"`
		AddressExtended  string   `json:"address_extended,omitempty"`
		AdminRegion      string   `json:"admin_region,omitempty"`
		CensusBlock      string   `json:"census_block,omitempty"`
		Country          string   `json:"country,omitempty"`
		CrossStreet      string   `json:"cross_street,omitempty"`
		Dma              string   `json:"dma,omitempty"`
		FormattedAddress string   `json:"formatted_address,omitempty"`
		Locality         string   `json:"locality,omitempty"`
		Neighborhood     []string `json:"neighborhood,omitempty"`
		PoBox            string   `json:"po_box,omitempty"`
		PostTown         string   `json:"post_town,omitempty"`
		Postcode         string   `json:"postcode,omitempty"`
		Region           string   `json:"region,omitempty"`
	} `json:"location,omitempty"`
	Menu          string                               `json:"menu,omitempty"`
	Name          string                               `json:"name,omitempty"`
	Photos        []AutoGenerated_Categories_Icon      `json:"photos,omitempty"`
	Popularity    float64                              `json:"popularity,omitempty"`
	Price         float64                              `json:"price,omitempty"`
	Rating        float64                              `json:"rating,omitempty"`
	RelatedPlaces AutoGenerated_Features_Amenities_Atm `json:"related_places,omitempty"`
	SocialMedia   struct {
		FacebookID string `json:"facebook_id,omitempty"`
		Instagram  string `json:"instagram,omitempty"`
		Twitter    string `json:"twitter,omitempty"`
	} `json:"social_media,omitempty"`
	Stats struct {
		TotalPhotos  float64 `json:"total_photos,omitempty"`
		TotalRatings float64 `json:"total_ratings,omitempty"`
		TotalTips    float64 `json:"total_tips,omitempty"`
	} `json:"stats,omitempty"`
	StoreID            string                              `json:"store_id,omitempty"`
	Tastes             []string                            `json:"tastes,omitempty"`
	Tel                string                              `json:"tel,omitempty"`
	Timezone           string                              `json:"timezone,omitempty"`
	Tips               []AutoGenerated_Categories_Icon_Tip `json:"tips,omitempty"`
	VenueRealityBucket string                              `json:"venue_reality_bucket,omitempty"`
	Verified           bool                                `json:"verified,omitempty"`
	Website            string                              `json:"website,omitempty"`
}

// AutoGenerated_Geocodes_DropOff is an aliased type from JSON.
type AutoGenerated_Geocodes_DropOff struct {
	Latitude  float64 `json:"latitude,omitempty"`
	Longitude float64 `json:"longitude,omitempty"`
}

// AutoGenerated_Features_Amenities_Atm is an aliased type from JSON.
type AutoGenerated_Features_Amenities_Atm any

// AutoGenerated_Hours_Regular is an aliased type from JSON.
type AutoGenerated_Hours_Regular struct {
	Close string  `json:"close,omitempty"`
	Day   float64 `json:"day,omitempty"`
	Open  string  `json:"open,omitempty"`
}

// AutoGenerated_Categories_Icon_Tip is an aliased type from JSON.
type AutoGenerated_Categories_Icon_Tip struct {
	AgreeCount    float64 `json:"agree_count,omitempty"`
	CreatedAt     string  `json:"created_at,omitempty"`
	DisagreeCount float64 `json:"disagree_count,omitempty"`
	ID            string  `json:"id,omitempty"`
	Lang          string  `json:"lang,omitempty"`
	Text          string  `json:"text,omitempty"`
	URL           string  `json:"url,omitempty"`
}

// AutoGenerated_Categories_Icon is an aliased type from JSON.
type AutoGenerated_Categories_Icon struct {
	Classifications []string                          `json:"classifications,omitempty"`
	CreatedAt       string                            `json:"created_at,omitempty"`
	Height          float64                           `json:"height,omitempty"`
	ID              string                            `json:"id,omitempty"`
	Prefix          string                            `json:"prefix,omitempty"`
	Suffix          string                            `json:"suffix,omitempty"`
	Tip             AutoGenerated_Categories_Icon_Tip `json:"tip,omitempty"`
	Width           float64                           `json:"width,omitempty"`
}
